gitea_version: "1.22.4"
gitea_download_url: "https://dl.gitea.io/gitea/{{ gitea_version }}/gitea-{{ gitea_version }}-linux-amd64"
gitea_install_dir: "/usr/local/bin"
gitea_user: "gitea"
gitea_group: "gitea"
gitea_home: "/var/lib/gitea"
gitea_data_dir: "/var/lib/gitea/data"
gitea_log_dir: "/var/log/gitea"
gitea_config_dir: "/etc/gitea"
