
---

- name: Check if SuiteCRM is already installed
  stat:
    path: "{{ suitecrm_install_dir }}/index.php"
  register: suitecrm_installed 

- name: Update package cache
  apt:
    update_cache: yes

- name: Install Apache Webserver packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ web_server_packages }}"
  when: not suitecrm_installed.stat.exists

- name: Enable Apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - rewrite
    - headers
  when: not suitecrm_installed.stat.exists

- name: Configure Apache virtual host
  template:
    src: suitecrm.conf.j2
    dest: /etc/apache2/sites-available/suitecrm.conf
  when: not suitecrm_installed.stat.exists

- name: Disable default Apache site
  command: a2dissite 000-default.conf   
  when: not suitecrm_installed.stat.exists 

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: yes